# Generated by Django 4.0.3 on 2022-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=13, unique=True)),
                ('itemKey', models.IntegerField(default=0)),
                ('datetimeCreated', models.DateTimeField(auto_now_add=True)),
                ('datetimeUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
